// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMyDatum = "my_data"

// MyDatum mapped from table <my_data>
type MyDatum struct {
	ID      int32  `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	Numbers string `gorm:"column:numbers;type:varchar(20);not null;index:idx_n,priority:1;default:0" json:"numbers"`
}

// TableName MyDatum's table name
func (*MyDatum) TableName() string {
	return TableNameMyDatum
}
