// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTicket = "tickets"

// Ticket mapped from table <tickets>
type Ticket struct {
	ID      int32  `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	Numbers string `gorm:"column:numbers;type:varchar(20);not null;index:idx_n,priority:1;default:0" json:"numbers"`
	Ymd     string `gorm:"column:ymd;type:varchar(8);uniqueIndex:idx_ymd,priority:1" json:"ymd"`
}

// TableName Ticket's table name
func (*Ticket) TableName() string {
	return TableNameTicket
}
